// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/career-redesign/DirectionA.tsx": () => import("../components/mockups/career-redesign/DirectionA.tsx"),
  "./components/mockups/career-redesign/DirectionB.tsx": () => import("../components/mockups/career-redesign/DirectionB.tsx")
};
